apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-tools-ubuntu
spec:
  selector:
    matchLabels:
      app: all-tools-ubuntu
  replicas: 1
  template:
    metadata:
      labels:
        app: all-tools-ubuntu
    spec:
      containers:
      - name: all-tools-ubuntu
        image: d4n13lbc/all-tools-ubuntu:v0.0.1
        ports:
        - containerPort: 5000