FROM ubuntu:bionic

RUN apt update -y

RUN apt install python3 python3-pip curl unzip -y

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install

RUN mkdir /python-server/
WORKDIR /python-server/

ADD python-server .
RUN pip3 install -r requirements.txt
ENV FLASK_APP=server.py

ENV LC_ALL=C.UTF-8 \
    LANG=C.UTF-8

CMD ["flask", "run", "-h", "0.0.0", "-p", "5000"]
